[package]
name = "zeroth-cli"
version.workspace = true
edition.workspace = true
description = "Command line tools for Zeroth"
license.workspace = true
homepage.workspace = true

[[bin]]
name = "zeroth"
path = "src/main.rs"

[dependencies]
base64.workspace = true
getrandom.workspace = true
p256.workspace = true
serde.workspace = true
serde_json.workspace = true
zeroth-server.workspace = true
zeroth-storage.workspace = true
